#Application
spring:
  application:
    name: ride-service
server:
  port: 8083


  #Postgres Database
  datasource:
    url: jdbc:postgresql://localhost:5432/ride_db
    username: ride_user
    password: ride_password

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  #Kafka
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      ride-matched: ride-matched
      ride-requested: ride-requested
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ride-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.rideshare.rideservice.event.RideMatchedEvent


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info